requires = ["tox>=4"]
env_list = ["lint", "type", "3.9", "3.10", "3.11", "3.12", "3.13"]

[env_run_base]
description = "Run unit tests"
deps = [
    "pytest>=8",
    "coverage>=7",
    "deepdiff>=8",
]
commands = [
    ["coverage", "run", "--branch", "-m", "unittest", "discover", "-v", { replace = "posargs", extend = true} ],
    ["coverage", "report", "-m", "--omit=tests/*", "--skip-empty", { replace = "posargs", extend = true} ],
    ["coverage", "xml", "--omit=tests/*", "--skip-empty", { replace = "posargs", extend = true} ],
]

[env.lint]
description = "Run linters for static code analysis"
deps = [
    "flake8>=7",
]
commands = [
    ["flake8", "standardbom", "tests"], { replace = "posargs", extend = true} ,
]

[env.type]
description = "Run type checker"
deps = [
    "mypy>=1.8",
    "types-python-dateutil>=2.8",
]
commands = [
    ["mypy", "-p", "standardbom", { replace = "posargs", extend = true} ],
]
