name: Python CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    call-build-and-test-workflow:
        uses:
            ./.github/workflows/build-and-test.yml
