# SPDX-FileCopyrightText: Copyright (c) Siemens AG 2019-2025 ALL RIGHTS RESERVED
# SPDX-License-Identifier: MIT

name: Python CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    call-build-and-test-workflow:
        uses:
            ./.github/workflows/build-and-test.yml
